trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  name: SelfHostedWin          
  demands:
    - Agent.OS -equals Windows_NT

variables:
  buildConfiguration: 'Release'
  solution: 'ConsoleApp.sln'   

steps:
  - checkout: self
    clean: true
    fetchDepth: 0